package com.flywaysafety.report;

import com.flywaysafety.analysis.AnalysisResult;
import com.flywaysafety.model.MigrationFile;
import com.flywaysafety.model.SafetyRating;

import java.util.List;
import java.util.Map;

public class MarkdownReportGenerator {

    public String generate(
            SafetyRating overallRating,
            Map<MigrationFile, AnalysisResult> results
    ) {
        StringBuilder sb = new StringBuilder();

        // Header
        sb.append("# Flyway Migration Safety Report\n\n");
        sb.append("**Overall Rating:** ").append(badge(overallRating)).append("\n\n");

        if (results.isEmpty()) {
            sb.append("No new migration files detected in this PR.\n\n");
        } else {
            sb.append("---\n\n");

            for (Map.Entry<MigrationFile, AnalysisResult> entry : results.entrySet()) {
                MigrationFile migration = entry.getKey();
                AnalysisResult result = entry.getValue();

                sb.append("## ").append(migration.filename())
                  .append("  ").append(badge(result.rating())).append("\n\n");

                // Rule findings
                if (!result.findings().isEmpty()) {
                    sb.append("**Rule Analysis:**\n");
                    for (String finding : result.findings()) {
                        sb.append("- ").append(finding).append("\n");
                    }
                    sb.append("\n");
                }

                // LLM explanation
                if (result.llmExplanation() != null && !result.llmExplanation().isBlank()) {
                    sb.append("**LLM Analysis:**\n\n");
                    sb.append("> ").append(result.llmExplanation().replace("\n", "\n> ")).append("\n\n");
                }

                sb.append("---\n\n");
            }
        }

        sb.append("*Generated by [flyway-safety-checker](https://github.com/anthropics/claude-code)*");
        return sb.toString();
    }

    private String badge(SafetyRating rating) {
        String label = rating.name();
        String color = rating.badgeColor();
        // shields.io badge: renders as a coloured image in GitHub PR comments
        return "![" + label + "](https://img.shields.io/badge/Safety-" + label + "-" + color + ")";
    }

    /**
     * Computes the worst (highest severity) rating across all results.
     */
    public static SafetyRating computeOverall(List<AnalysisResult> results) {
        SafetyRating worst = SafetyRating.GREEN;
        for (AnalysisResult r : results) {
            worst = SafetyRating.worst(worst, r.rating());
        }
        return worst;
    }
}
